### ISSUE TITLE
JSTL issues with version 1.2.0

### ISSUE THREAD

**Issue by altrunner** [guikeller/jetty-runner#30] opened 2016-10-06 09:58 UTC
With 1.2.0 web application returns: 
org.apache.jasper.JasperException: The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:55) at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:277) at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:75) 
After roll-back to 1.1.3 all went to normal.

**Comment by guikeller** [comment] 2016-10-06 23:52
Hi @altrunner 

Thank you very much for reporting the issue! :+1: 

After further investigation it seems that on versions of Jetty 9.3.x and above they have removed the **jetty-webapp.jar** and **jetty-jsp.jar** out of the **jetty-runner.jar** causing this issue.

Would you mind trying to run the plugin v1.2.0 adding the following extra jars to your classpath before booting up your webapp:
_jetty-webapp-9.3.11.v20160721.jar_
_jetty-jsp-9.2.18.v20160721.jar_

Here are the links to download the extra jar files:
https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-webapp/9.3.11.v20160721
https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-jsp/9.2.18.v20160721

---

Alternatively, rolling back to v1.1.3 is definitely a must and only solution in the meantime.

**NOTE**: I am extremely busy with work and I don't think that I will have time to look into this issue any time soon. _Pull Requests_ are more than welcome, thank you very much for your understanding.

Cheers,
Gui

**Comment by guikeller** [comment] 2016-10-12 05:22
Hi @altrunner ,

Any luck with any of the suggestions above? 
It could also be a simple classpath issue; try adding the **jstl.jar** there.

Could you please let me know how you go? :smiley: 
If I receive no updates on this I will simply close this issue as I can't reproduce it.

Cheers,
Gui

**Comment by altrunner** [comment] 2016-10-12 09:47
Hi,

Sorry for the late answer, I'm a bit bussy this week.
Will try suggested work-around as soon as I have a spare minute.

Thank you!

**Comment by altrunner** [comment] 2016-10-12 15:44
I've added  suggested libraries as maven dependencies to my application and things got eve worst:

Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/util/thread/NonBlockingThread
	at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:258)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)

**Comment by guikeller** [comment] 2016-10-18 01:49
Hi @altrunner 

Seems like another classpath dependency issue - **NoClassFoundError**.
Missing class is: _org/eclipse/jetty/util/thread/NonBlockingThread_

Please add the following extra jar to your classpath:
https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-util/9.3.11.v20160721

Thank you for your help and cooperation with the issue.
Let me know how you go please :+1: 

Cheers,
Gui

**Comment by guikeller** [comment] 2016-10-30 21:43
Hi @altrunner,

Any news on the classpath issue?
Again, thank you very much for your collaboration.

Cheers,
Gui

**Comment by guikeller** [comment] 2016-11-07 02:01
Closing the issue as no further updates have been provided.
Also, no one else has reported to be having the same problem.

It seems that adding some extra jar files to the classpath have fixed the issue - here the list:
https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-webapp/9.3.11.v20160721
https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-util/9.3.11.v20160721
https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-jsp/9.2.18.v20160721

Alternatively, the plugin v1.1.3 can be used and works fine.

Cheers,
Gui

**Closed by guikeller** 2016-11-07 02:01 UTC
Labels: bug, enhancement, help wanted
