### ISSUE TITLE
Plugin always fails with java.lang.NoSuchMethodError: javax.servlet.ServletContext.getServletRegistration

### ISSUE THREAD

**Issue by layeeq** [guikeller/jetty-runner#20] opened 2015-11-16 01:42 UTC
When i run the jetty server then i get this exception

Exception in thread "main" java.lang.NoSuchMethodError: javax.servlet.ServletContext.getServletRegistration(Ljava/lang/String;)Ljavax/servlet/ServletRegistration;
        at org.apache.jasper.runtime.TldScanner.onStartup(TldScanner.java:231)
        at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:106)
        at org.eclipse.jetty.annotations.ServletContainerInitializerListener.contextInitialized(ServletContainerInitializerListener.java:107)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:775)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:767)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:710)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:492)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
        at org.eclipse.jetty.server.Server.doStart(Server.java:280)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.mortbay.jetty.runner.Runner.run(Runner.java:512)
        at org.mortbay.jetty.runner.Runner.main(Runner.java:633)

I tried 1.1.2 0.6 and 0.2 but still i see this same error. I am using IntellijIDEA 14.1.5

i am using servlet api 2.5 jar so 0.6 onwards the plugin should work but not sure why it is failing.

How do i installed jetty-runner plugin to Idea:
1) open Preferences -> Plugins -> Install plugin from disk... then select the file jetty-runner.jar downloaded from internet
2) now copy the jetty-runner-8.1.9.v20130131.jar and paste here "IntelliJ IDEA 14 CE" -> Contents -> lib
3) now configure Jetty Runner application inside Idea edit configurations and start the server

**Comment by fidransky** [comment] 2015-11-24 13:25
Same here.

Idea 15.0.1 CE, Jetty Runner 1.1.2

**Comment by fidransky** [comment] 2015-11-25 16:25
OK, in my case, this was caused by multiple servlet-api versions being used by project's dependencies. Excluding one of them solved the issue.

**Comment by guikeller** [comment] 2015-11-28 02:22
Thanks a lot @fidransky for you collaboration!
I am going to close the issue as it's not a bug with the plugin, cheers.

**Closed by guikeller** 2015-11-28 02:22 UTC
