### ISSUE TITLE
NoClassDefFoundError reported in Intellij Idea 14

### ISSUE THREAD

**Issue by ngloom** [guikeller/jetty-runner#6] opened 2015-03-06 10:54 UTC
HI, Guikeller 

First of all , thanks for your excellent work.

i'm run jetty runner on my intellij idea 14 today and find the error below:

NoClassDefFoundError: Could not initialize class com.github.guikeller.jettyrunner.runner.JettyRunnerCommandLine

google it without find anything valuable, what to do to make it run ?

the details is as below :
 
Could not initialize class com.github.guikeller.jettyrunner.runner.JettyRunnerCommandLine
java.lang.NoClassDefFoundError: Could not initialize class com.github.guikeller.jettyrunner.runner.JettyRunnerCommandLine
	at com.github.guikeller.jettyrunner.model.JettyRunnerConfiguration.getState(JettyRunnerConfiguration.java:57)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:201)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:58)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:53)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:94)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:375)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:60)
	at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:368)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

Thanks again.

**Comment by guikeller** [comment] 2015-03-07 05:48
Hi ngloom,

Thanks for the kind words and reporting the bug to me!
"Could not initialize class com.github.guikeller.jettyrunner.runner.JettyRunnerCommandLine".

It seems that the plugin may not be compatible with the IntelliJ version that you're running.
Could you please provide a screenshot of your configuration and the version of IntelliJ that you're using?

Cheers,
Gui

**Comment by ngloom** [comment] 2015-03-08 00:09
HI, guikeller:
My Intellij Idea version is 14.0.3  running on with jre1.6.0_65;
my project configuration is as below : 
![image](https://cloud.githubusercontent.com/assets/495831/6543853/610b77f6-c56a-11e4-89b1-b8e021d7ee94.png)

**Comment by guikeller** [comment] 2015-03-08 19:38
Hi ngloom,

Thanks for the information, I've managed to replicate the bug; the new version of IntelliJ breaks backwards compatibility. I should be able to fix it today and push a new version of the plugin out very soon.

Kind regards,
Gui

**Comment by ngloom** [comment] 2015-03-09 09:17
Hi, Guikerller:

Looking forward to the new version !

Thanks for the immediate reply, again ~~~

Wish you have a nice day  : )

**Comment by guikeller** [comment] 2015-03-15 21:16
Hi ngloom,

I managed to replicate bug once only and it sorted itself out somehow (?)
Tried again on the weekend and didn't manage to replicate it.

One thing I've noticed is that you're using Java 6 and Jetty 9.1 requires Java 7.
http://en.wikipedia.org/wiki/Jetty_%28web_server%29

Could you please try the following below (in order):
1. Upgrade to Java (JDK) 7 
2. Uninstall / install the plugin

Hope it helps you sort out this issue.

King regards,
Gui

**Comment by guikeller** [comment] 2015-03-21 01:29
Closing this issue as I was not able to replicate the bug.
I hope that upgrading to Java 7 and uninstalling / installing the plugin has solved the issue.

**Closed by guikeller** 2015-03-21 01:29 UTC

**Comment by mostafaelganainy** [comment] 2015-05-17 21:14
Thanks guikeller for your nice work.

I had the same issues as in issue #6 & #11 , and fixed them.

The root cause for both issues, are the difference in JDK version used to build the plugin and the Java version under which the users are running intellij. The plugin seems to be built with Java 1.7, so in my case I found my intellij running under Java 1.6. 

To change the JDK version under which my intellij (v. 14) is running, I followed the following article : https://intellij-support.jetbrains.com/entries/23455956-Selecting-the-JDK-version-the-IDE-will-run-under

**Comment by guikeller** [comment] 2015-05-18 02:45
Hi mostafaelganainy,

Thank you very much for your kind words and for sharing your findings around this issue.
I am glad that you have found the culprit and that it's only a JVM compatibility issue.

However, I do state on the website:
https://plugins.jetbrains.com/plugin/7505
"**PS: Minimum requirement since v0.0.7 - JVM7.**"

Thank you very much for your collaboration.

Kind regards,
Gui
