### ISSUE TITLE
Add IntelliJ 2020.1 compatibility

### ISSUE THREAD

**Issue by simon04** [guikeller/jetty-runner#70] opened 2020-02-15 23:06 UTC
Using IntelliJ EAP 2020.1.201.5259.13-1, I get the following exception:

```
com.intellij.diagnostic.PluginException: While loading class com.github.guikeller.jettyrunner.runner.JettyProgramDebugger: com/intellij/debugger/impl/GenericDebuggerRunner [Plugin: JettyRunner-GK]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:80)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:39)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:68)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:431)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:418)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.access$100(ExtensionPointImpl.java:36)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl$1.next(ExtensionPointImpl.java:326)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl$RunnerItem.findRunner(RunnerAndConfigurationSettingsImpl.kt:589)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl$RunnerItem.loadState(RunnerAndConfigurationSettingsImpl.kt:464)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:230)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.readData(RunConfigurationSchemeManager.kt:65)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:48)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:22)
	at com.intellij.configurationStore.LazySchemeProcessor.createScheme$default(scheme-impl.kt:65)
	at com.intellij.configurationStore.schemeManager.SchemeLoader.loadScheme(schemeLoader.kt:175)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:193)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:42)
	at com.intellij.configurationStore.SchemeManagerIprProvider.processChildren(SchemeManagerIprProvider.kt:48)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:191)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.reload(SchemeManagerImpl.kt:252)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:664)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:68)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:409)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:360)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:131)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:97)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:49)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.kt:304)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:59)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:15)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$$inlined$use$lambda$1.run(ServiceComponentAdapter.kt:47)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:626)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:571)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:187)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:46)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.doGetService(PlatformComponentManagerImpl.kt:343)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:330)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer.serviceCreated(ProjectRunConfigurationInitializer.kt:28)
	at com.intellij.openapi.project.ProjectLoadHelper$Companion$notifyThatComponentCreated$$inlined$runHandler$1.accept(projectLoader.kt:109)
	at com.intellij.openapi.project.ProjectLoadHelper$Companion$notifyThatComponentCreated$$inlined$runHandler$1.accept(projectLoader.kt)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:281)
	at com.intellij.openapi.project.ProjectLoadHelper$Companion.notifyThatComponentCreated(projectLoader.kt:113)
	at com.intellij.openapi.project.ProjectLoadHelper.notifyThatComponentCreated(projectLoader.kt)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:281)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:314)
	at com.intellij.platform.PlatformProjectOpenProcessorKt.convertAndLoadProject(PlatformProjectOpenProcessor.kt:416)
	at com.intellij.platform.PlatformProjectOpenProcessorKt.prepareProject(PlatformProjectOpenProcessor.kt:312)
	at com.intellij.platform.PlatformProjectOpenProcessorKt.access$prepareProject(PlatformProjectOpenProcessor.kt:1)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$openExistingProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(PlatformProjectOpenProcessor.kt:183)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$openExistingProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(PlatformProjectOpenProcessor.kt:58)
	at com.intellij.platform.ProjectUiFrameAllocator$run$1$$special$$inlined$createModalTask$1.run(progress.kt:37)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:931)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:481)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:75)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:626)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:571)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:245)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/intellij/debugger/impl/GenericDebuggerRunner
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:380)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:376)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:340)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:259)
	... 74 more
Caused by: java.lang.ClassNotFoundException: com.intellij.debugger.impl.GenericDebuggerRunner PluginClassLoader[JettyRunner-GK, 1.3.1] com.intellij.ide.plugins.cl.PluginClassLoader@13487be2
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 81 more
```

**Comment by guikeller** [comment] 2020-02-16 07:57
Hi @simon04 

It seems that they have removed the **GenericDebuggerRunner** on IntelliJ 2020.1 EAP
`java.lang.ClassNotFoundException: com.intellij.debugger.impl.GenericDebuggerRunner`

I have been getting compatibility e-mails from Jetbrains lately.
So far they have not detected anything that breaks this plugin.

Do you see the same exception on IntelliJ CE 2019.3.3?
Can you not wait for IntelliJ CE 2020.1.1?

Cheers, Gui

**Comment by simon04** [comment] 2020-02-16 12:03
Hi @guikeller,

interestingly the file is still around, https://github.com/JetBrains/intellij-community/blob/idea/201.5259.13/java/debugger/impl/src/com/intellij/debugger/impl/GenericDebuggerRunner.java

Thanks, Simon

**Comment by ilittle-cnri** [comment] 2020-04-09 15:06
I just updated to the release version of 2020.1, and ran into this issue. No problem before, on the 2019.3 version.

**Comment by onaralili** [comment] 2020-04-11 07:28
Updated to 2020.1 and got the same issue. It was working on 2019.x

**Comment by guikeller** [comment] 2020-04-11 07:38
Interesting, I will upgrade my IntelliJ to 2020 and fix the issue, thanks for reporting.

**Comment by guikeller** [comment] 2020-04-11 16:35
@simon04  @ilittle-cnri @onaralili 

Would you be able to install from this zip file and confirm if the debugger is working or not?
https://drive.google.com/open?id=1Ysn8u3Abntpx4hlZEgfIRoWBKU-CvAox

I got it to work once, then it completely stopped working, could be something weird on my side.
Otherwise, I will raise a bug with Jetbrains, let's see.

If all goes well I will publish it officially.
Thanks! 😄 

PS: code changes have already been committed and pushed in case you're interested

**Comment by Pashk88** [comment] 2020-04-13 12:06
@guikeller, Hi!

I have tested 1.4.13 with IntelliJ IDEA 2020.1 (Community Edition #IC-201.6668.121) and it works without exceptions, but debugger does not work.

**Comment by Pashk88** [comment] 2020-04-13 12:37
Workaround for Java 8
1) add VM args in Jetty Runner
`-Xdebug
-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044`
2) launch application and then Attach Debugger

**Comment by guikeller** [comment] 2020-04-14 02:49
@Pashk88 

Thanks for testing that and for providing a workaround.
It is weird that by adding those VM args the debugger works.

I say that because this is exactly what L63 does here:
https://github.com/guikeller/jetty-runner/blob/master/src/main/java/com/github/guikeller/jettyrunner/runner/JettyProgramDebugger.java

I will raise a bug with JetBrains/IntelliJ and see what they say about it.

**Comment by ilittle-cnri** [comment] 2020-04-14 12:51
Debugging works for me on the new version, but only after not working once. So, on the first debug run I started a debug run, it didn't hit any breakpoints. However, it has worked as expected on subsequent runs. Also, If I switch Jetty versions, I again have one non-working run before the debugger works as expected.

I'm using Java 8 in the runner. Did not need to change any VM args. Simply stopping the run and trying again worked.

**Comment by guikeller** [comment] 2020-04-15 10:25
Well, that definitely sounds like an upstream bug/issue, but I can be wrong.
Let's wait and see what the guys from Jetbrains have got to say. 👍

**Comment by develar** [comment] 2020-04-28 11:41
CNFE Issue caused by change in IJ Platform PluginManagerCore logic — now `<depends>com.intellij.java</depends>` is required to add Java plugin to classpath of your model. As I can see, it is already fixed.

I cannot reproduce 

> GenericDebuggerRunner is modifying the "JavaCommandLine" VMParametersList after the " createContentDescriptor" is executed.

**Comment by develar** [comment] 2020-04-28 12:04
Debug doesn't work in a new version of plugin, because `GenericDebuggerRunner` is not used anymore as a parent class. Please revert corresponding change. As I commented above, `<depends>com.intellij.java</depends>` is the only required change to fix compatibility.

Sorry, that IJ Platform evolution affects you, we do our best to not preserve backward compatibility.

**Comment by guikeller** [comment] 2020-04-29 00:10
@develar 

Quick recap.
1. The required changes have already been done (add `<depends>com.intellij.java</depends>` to plugin.xml)
2. You could not reproduce the bug, even though others have reported here of the bug.

Okay then, I will release the plugin as-is and close the bug. Cheers!

**Closed by guikeller** 2020-04-29 00:10 UTC
Labels: enhancement, help wanted, pr-wanted

**Comment by guikeller** [comment] 2020-04-29 01:27
The plugin has been released as-is; probably its very last version.
I have absolutely no motivation to carry on with it after 5+ years.

**Comment by develar** [comment] 2020-04-29 06:07
@guikeller Please see my comment https://github.com/guikeller/jetty-runner/issues/70#issuecomment-620563416

> Debug doesn't work in a new version of plugin, because GenericDebuggerRunner is not used anymore as a parent class. Please revert corresponding change

I tested version from google drive.

**Comment by guikeller** [comment] 2020-04-29 07:21
The previous version of the plugin also used the GenericDebuggerRunner.
See: https://github.com/guikeller/jetty-runner/commit/9de4f2f61137dc3846c7b585554c0fdd8c3ab18b#diff-15a1da58f27c87cec8d4431ee3411c3c

Should I extend/inherit another class?

---
The zip from google drive is what has been published to plugins.jetbrains.com

**Comment by develar** [comment] 2020-04-29 07:33
> Should I extend/inherit another class?

No, no changes are required for `JettyProgramDebugger.java` and `GenericDebuggerRunner` should be used here as before.

The only change to make plugin working for a new version of IDEA — adding `<depends>com.intellij.java</depends>`.

**Comment by guikeller** [comment] 2020-04-29 07:36
> The only change to make plugin working for a new version of IDEA - adding <depends>com.intellij.java</depends>

Oh yeah, that has been done to the plugin.xml so it should be all good then.
Thanks for your help @develar

**Comment by 86jkuncle** [comment] 2020-05-29 06:17
@guikeller  I just upgraded to idea 2020.1.1, and the downloaded jetty-runner version is 1.4.13, the debugger still does not work

**Comment by 86jkuncle** [comment] 2020-05-29 06:24
I must add the VM parameter -Xdebug -Xrunjdwp: transport = dt_socket, server = y, suspend = n, address = 1044, start in debug mode, manually click Attach Debugger to make debug work properly

**Comment by 86jkuncle** [comment] 2020-05-29 06:33
by the way,I use the free community version,The version number is 2020.1.1,Build #IC-201.7223.91

**Comment by guikeller** [comment] 2020-05-29 06:38
hi @86jkuncle 

Please read this thread from the beginning and follow the links.

Thanks.
