### ISSUE TITLE
run ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by fanliukund** [guikeller/jetty-runner#11] opened 2015-05-04 12:31 UTC
null
java.lang.ExceptionInInitializerError
	at com.github.guikeller.jettyrunner.model.JettyRunnerConfiguration.getState(JettyRunnerConfiguration.java:57)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:201)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:58)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:53)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:94)
	at com.intellij.execution.impl.ExecutionManagerImpl.start(ExecutionManagerImpl.java:396)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:61)

**Comment by fanliukund** [comment] 2015-05-04 12:36
intellij14.1.2
NoClassDefFoundError: Could not initialize class com.github.guikeller.jettyrunner.runner.JettyRunnerCommandLine

**Comment by guikeller** [comment] 2015-05-04 21:25
Hi fanliukund,

Please see Issue #6 - it looks like that you're having the same issue.
I could not replicate the bug last time unfortunately..

Try uninstalling / installing the plugin.
The more info that you provide the better, steps to reproduce the problem, etc.

Kind regards,
Gui

**Comment by guikeller** [comment] 2015-05-14 22:23
It has been 10 (ten) days without any feedback on this.
Closing the issue; "won't fix" as I can't reproduce it.

**Closed by guikeller** 2015-05-14 22:23 UTC
Labels: bug, duplicate, help wanted
